from dataclasses import dataclass


@dataclass
class MemoryCandidate:
    """
    Proposed memory generated by the LLM.
    It has NOT been accepted into long-term memory yet.
    """

    memory_type: str
    category: str
    key: str
    value: str

    importance: float
    confidence: float